CREATE TABLE dbo.SampleSuperstore (
    RowID INT NULL,
    OrderID NVARCHAR(50) NULL,
    OrderDate DATE NULL,
    ShipDate DATE NULL,
    ShipMode NVARCHAR(50) NULL,
    CustomerID NVARCHAR(50) NULL,
    CustomerName NVARCHAR(100) NULL,
    Segment NVARCHAR(50) NULL,
    Country NVARCHAR(50) NULL,
    City NVARCHAR(100) NULL,
    State NVARCHAR(100) NULL,
    PostalCode NVARCHAR(20) NULL,
    Region NVARCHAR(50) NULL,
    ProductID NVARCHAR(50) NULL,
    Category NVARCHAR(50) NULL,
    SubCategory NVARCHAR(50) NULL,
    ProductName NVARCHAR(200) NULL,
    Sales DECIMAL(18,2) NULL,
    Quantity INT NULL,
    Discount DECIMAL(5,2) NULL,
    Profit DECIMAL(18,2) NULL
);
